### ISSUE TITLE
Support for badges

### ISSUE THREAD

**Issue by jlucktay** [posener/goreadme#77]
Hi there, I can see some code and templates and such around handling badges (Travis CI, GoDoc, GolangCI, etc) but it doesn't seem to be fully wired up.
I'd like to use `goreadme` for some of my own packages/repos, but would really miss my badges if they weren't handled by a tool like this and ended up going away.
Is this something that will be covered in the near future? I'm more than happy to help out with a PR on this.

**Comment by posener** [comment]
Hi

The available badges are available here: https://github.com/posener/goreadme/blob/master/goreadme.go#L95
They are currently can't be added with the command line, but you can add this option here: https://github.com/posener/goreadme/blob/master/cmd/goreadme/main.go#L23
If you want to add a new badge, it can be added in the template here: https://github.com/posener/goreadme/blob/master/internal/template/template.go#L45

If you are using https://goreadme.herokuapp.com, you can provide the badge configuration in a `goreadme.json` file in the root directory of your project. For example: https://github.com/posener/goreadme/blob/master/goreadme.json.

**Comment by bakerolls** [comment]
Hi, I'd like to have this feature, too. Do you think adding flags like `-badge-goreadme` would be ok? 

If so, we could check if a given import path (not a relative one) exist in the `GOPATH` and, if yes, use `gosrc.SetLocalDevMode(os.Getenv("GOPATH"))` inside your `docGet` to fetch its metadata.

Am I missing something obvious?

**Comment by posener** [comment]
Hi

> Hi, I'd like to have this feature, too. Do you think adding flags like `-badge-goreadme` would be ok?

Sure

> If so, we could check if a given import path (not a relative one) exist in the `GOPATH` and, if yes, use `gosrc.SetLocalDevMode(os.Getenv("GOPATH"))` inside your `docGet` to fetch its metadata.

I am not sure what is the relation between `SetLocalDevMode` to badge flags.

**Comment by bakerolls** [comment]
Sorry, I didn't notice that you are using `GITHUB_TOKEN` to authenticate against GitHubs API. With that set, adding flags, as you said, is enough. Thank you!

**Comment by posener** [comment]
Fixed by #78
