### ISSUE TITLE
Obsolete dependency on posener/goaction v1.0.3

### ISSUE THREAD

**Issue by paskal** [posener/goreadme#92]
Hi there, that's what I see when I try to replicate installation command from Readme in an existing project:
```
$ go version
go version go1.14.2 darwin/amd64
$ GO111MODULE=on go get github.com/posener/goreadme/cmd/goreadme
go: downloading github.com/posener/goreadme v1.3.2
go: found github.com/posener/goreadme/cmd/goreadme in github.com/posener/goreadme v1.3.2
go get: github.com/posener/goreadme@v1.3.2 requires
	github.com/posener/goaction@v1.0.3: reading github.com/posener/goaction/go.mod at revision v1.0.3: unknown revision v1.0.3
```

**Comment by posener** [comment]
Hey
Thanks.
Yes, the goaction 1.0.3 was a "pre release", The dependency can be updated to [v0.1.0](https://github.com/posener/goaction/releases/tag/v0.1.0).
Do you want to submit a PR?

**Comment by paskal** [comment]
I've figured out how to use it by building locally and then using binary directly, my problem is solved. I would skip creating a PR if you don't mind, as your tags scheme seems complex and I don't understand what led to this situation and how to improve it, and I don't want to just bluntly do what you proposed without understanding.

**Comment by posener** [comment]
Glad to hear that your problem was solved.
I see that the go.mod is good, just pushed a new release v1.3.3 that this issue should be fixed in.
