### ISSUE TITLE
Generated file notice in raw MD file

### ISSUE THREAD

**Issue by thaney071** [posener/goreadme#99]
It would be nice if the tool could add a comment to the .md output as an html comment so that it is clear that the file is generated and should not be directly edited. This is most useful in team projects were others may not be aware of this tool and make edits to the file directly.

**Comment by posener** [comment]
This could be added to the template [here](https://github.com/posener/goreadme/blob/master/internal/template/template.go#L58)
Would you like to submit a PR?

**Comment by alexandregv** [comment]
Since this issue is now from 3 years ago, I took the liberty to open a PR for it: #132
